spring.application.name=Production
server.port=8083
spring.datasource.url=jdbc:postgresql://localhost:5432/CMMS?currentSchema=CmmsTables
spring.datasource.username=postgres
spring.datasource.password=password
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# Specify the default custom schema for entities
spring.jpa.properties.hibernate.default_schema=corporate

spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.hbm2ddl.create_namespaces=true
# Format and log SQL queries in the console
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# 1. Target Microservice Endpoints
# Use this property in your @FeignClient(url = "${services.master-service.url}")
services.master-service.url=http://localhost:8081/api/v1

# 2. Global Feign Settings (Applies to all clients)
spring.cloud.openfeign.client.config.default.connect-timeout=5000
spring.cloud.openfeign.client.config.default.read-timeout=5000

# 3. Client-Specific Configurations (Overrides default for master-service)
spring.cloud.openfeign.client.config.master-service.connect-timeout=3000
spring.cloud.openfeign.client.config.master-service.read-timeout=3000
spring.cloud.openfeign.client.config.master-service.logger-level=full

# 4. HTTP Request & Response Tracing (Prints to Console)
level.com.cmms.production.feignClients=DEBUG

# 5. Fault Tolerance & Circuit Breaker Support
spring.cloud.openfeign.circuitbreaker.enabled=true
spring.jpa.properties.hibernate.globally_quoted_identifiers=true
spring.cloud.openfeign.client.config.default.connectTimeout=5000
spring.cloud.openfeign.client.config.default.readTimeout=5000

spring.cloud.openfeign.client.config.default.loggerLevel=FULL
spring.cloud.openfeign.client.config.inventory-service.connectTimeout=2000
spring.cloud.openfeign.client.config.inventory-service.url=http://localhost:8083

resend.api.key=re_cmDrmTD2_8LTcnwdofphoBfzyphenbr5T

